Data = 	\
{
	'WNDPROC_EX': 'pcode',
	'PUINT': 'pint32',
	'FXPT2DOT30': 'int32',
	'COLORREF': 'int32',
	'LPCOLORREF': 'pint32',
	'PCOLORREF': 'pint32',
	'INT': 'int32',
	'PALETTEENTRY': 'int32',
	'FLONG': 'int32',
	'PFLONG': 'pint32',
	'LFTYPE': 'int32',
	'TCHAR': 'int16',
	'COLOR16': 'int16',
	'LPWORD': 'pint16',
	'LPDWORD': 'pint32',
	'PFONT_FILE_INFO': 'pbuf',
	'FULLSCREENCONTROL': 'int32',
	'FLATPTR': 'int32',
	'ULONG_PTR': 'int32',
	'UINT_PTR': 'int32',
	'LCSCSTYPE': 'int32',
	'LCSGAMUTMATCH': 'int32',
	'BLENDFUNCTION': 'int32',
	'WPARAM': 'int32',
	'LPARAM': 'int32',
	'PFONT_REALIZATION_INFO': 'pbuf',
	'HKL': 'int32',
	'PHKL': 'pint32',
	'ATOM': 'int16',
	'WNDPROC': 'pcode',
	'DHSURF': 'pbuf',
	'DHPDEV': 'pbuf',
	'ROP4': 'int32',
	'MIX': 'int32',
	'PLUID': 'int16',
	'PSID': 'pbuf',
	'WINEVENTPROC': 'pcode',
	'HOOKPROC': 'pcode',
	'FLOAT_LONG': 'int32',
	'FLOATL': 'int32',
	'PFLOAT_LONG': 'pint32',
	'FIX': 'int32',
	'PPVOID': 'ppbuf',

	#enums
	'CONSOLECONTROL': 'int32',
	'ARCTYPE': 'int32',
	'GETCPD': 'int32',
	'USERTHREADINFOCLASS': 'int32',
	'HLSURF_INFORMATION_CLASS': 'int32',
}